In [23]:
import pandas as pd

In [24]:
df=pd.read_csv("D:/Programs/CodSoft/Fraud/fraudTest.csv")

In [25]:
df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [26]:
df['city'].is_unique

False

In [27]:
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,...,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
555715,555715,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,...,29.0393,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
555716,555716,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,...,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
555717,555717,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,...,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
555718,555718,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,...,35.6665,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

In [28]:
df=df.drop(['Unnamed: 0', 'street','first', 'last','street', 'city', 'state', 'zip','dob','merchant'],axis=1)

In [29]:
df

,trans_date_trans_time,cc_num,category,amt,gender,lat,long,city_pop,job,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2020-06-21 12:14:25,2291163933867244,personal_care,2.86,M,33.9659,-80.9355,333497,Mechanical engineer,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,2020-06-21 12:14:33,3573030041201292,personal_care,29.84,F,40.3207,-110.4360,302,"Sales professional, IT",324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2020-06-21 12:14:53,3598215285024754,health_fitness,41.28,F,40.6729,-73.5365,34496,"Librarian, public",c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,2020-06-21 12:15:15,3591919803438423,misc_pos,60.05,M,28.5697,-80.8191,54767,Set designer,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,2020-06-21 12:15:17,3526826139003047,travel,3.19,M,44.2529,-85.0170,1126,Furniture designer,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,2020-12-31 23:59:07,30560609640617,health_fitness,43.77,M,40.4931,-91.8912,519,Town planner,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
555715,2020-12-31 23:59:09,3556613125071656,kids_pets,111.84,M,29.0393,-95.4401,28739,Futures trader,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
555716,2020-12-31 23:59:15,6011724471098086,kids_pets,86.88,F,46.1966,-118.9017,3684,Musician,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
555717,2020-12-31 23:59:24,4079773899158,travel,7.99,M,44.6255,-116.4493,129,Cartographer,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
555718,2020-12-31 23:59:34,4170689372027579,entertainment,38.13,M,35.6665,-97.4798,116001,Media buyer,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

In [30]:
df['gender'] = df['gender'].map({'M': 0, 'F': 1})

In [31]:
df

,trans_date_trans_time,cc_num,category,amt,gender,lat,long,city_pop,job,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2020-06-21 12:14:25,2291163933867244,personal_care,2.86,0,33.9659,-80.9355,333497,Mechanical engineer,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,2020-06-21 12:14:33,3573030041201292,personal_care,29.84,1,40.3207,-110.4360,302,"Sales professional, IT",324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2020-06-21 12:14:53,3598215285024754,health_fitness,41.28,1,40.6729,-73.5365,34496,"Librarian, public",c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,2020-06-21 12:15:15,3591919803438423,misc_pos,60.05,0,28.5697,-80.8191,54767,Set designer,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,2020-06-21 12:15:17,3526826139003047,travel,3.19,0,44.2529,-85.0170,1126,Furniture designer,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,2020-12-31 23:59:07,30560609640617,health_fitness,43.77,0,40.4931,-91.8912,519,Town planner,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
555715,2020-12-31 23:59:09,3556613125071656,kids_pets,111.84,0,29.0393,-95.4401,28739,Futures trader,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
555716,2020-12-31 23:59:15,6011724471098086,kids_pets,86.88,1,46.1966,-118.9017,3684,Musician,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
555717,2020-12-31 23:59:24,4079773899158,travel,7.99,0,44.6255,-116.4493,129,Cartographer,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
555718,2020-12-31 23:59:34,4170689372027579,entertainment,38.13,0,35.6665,-97.4798,116001,Media buyer,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

In [32]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
df = pd.concat([df, pd.DataFrame(ohe.fit_transform(df[['category']]).toarray(), columns=ohe.categories_[0])], axis=1)
df = df.drop(['category'], axis=1)

In [33]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
df = pd.concat([df, pd.DataFrame(ohe.fit_transform(df[['job']]).toarray(), columns=ohe.get_feature_names_out())], axis=1)
df = df.drop(['job'], axis=1)

In [34]:
df

,trans_date_trans_time,cc_num,amt,gender,lat,long,city_pop,trans_num,unix_time,merch_lat,...,job_Video editor,job_Visual merchandiser,job_Volunteer coordinator,job_Warden/ranger,job_Waste management officer,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer
0,2020-06-21 12:14:25,2291163933867244,2.86,0,33.9659,-80.9355,333497,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-06-21 12:14:33,3573030041201292,29.84,1,40.3207,-110.4360,302,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-06-21 12:14:53,3598215285024754,41.28,1,40.6729,-73.5365,34496,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-06-21 12:15:15,3591919803438423,60.05,0,28.5697,-80.8191,54767,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-06-21 12:15:17,3526826139003047,3.19,0,44.2529,-85.0170,1126,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,2020-12-31 23:59:07,30560609640617,43.77,0,40.4931,-91.8912,519,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
555715,2020-12-31 23:59:09,3556613125071656,111.84,0,29.0393,-95.4401,28739,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
555716,2020-12-31 23:59:15,6011724471098086,86.88,1,46.1966,-118.9017,3684,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
555717,2020-12-31 23:59:24,4079773899158,7.99,0,44.6255,-116.4493,129,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
555718,2020-12-31 23:59:34,4170689372027579,38.13,0,35.6665,-97.4798,116001,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
import calendar
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])
df['day_of_week'] = df['trans_date_trans_time'].dt.dayofweek
df['day_of_week'] = df['day_of_week'].apply(lambda x: 'Weekday' if x<5 else 'Weekend')
df['hour_of_day'] = df['trans_date_trans_time'].dt.hour
df['hour_of_day'] = df['hour_of_day'].apply(lambda x: 'Morning' if x<12 else ('Afternoon' if x<17 else 'Evening'))
df['month'] = df['trans_date_trans_time'].dt.month
df['month'] = df['month'].apply(lambda x: calendar.month_name[x])
df['year'] = df['trans_date_trans_time'].dt.year
df['day_of_month'] = df['trans_date_trans_time'].dt.day
df['day_of_month'] = df['day_of_month'].apply(lambda x: 'First Half' if x<16 else 'Second Half')

In [36]:
df

,trans_date_trans_time,cc_num,amt,gender,lat,long,city_pop,trans_num,unix_time,merch_lat,...,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer,day_of_week,hour_of_day,month,year,day_of_month
0,2020-06-21 12:14:25,2291163933867244,2.86,0,33.9659,-80.9355,333497,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,...,0.0,0.0,0.0,0.0,0.0,Weekend,Afternoon,June,2020,Second Half
1,2020-06-21 12:14:33,3573030041201292,29.84,1,40.3207,-110.4360,302,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,...,0.0,0.0,0.0,0.0,0.0,Weekend,Afternoon,June,2020,Second Half
2,2020-06-21 12:14:53,3598215285024754,41.28,1,40.6729,-73.5365,34496,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,...,0.0,0.0,0.0,0.0,0.0,Weekend,Afternoon,June,2020,Second Half
3,2020-06-21 12:15:15,3591919803438423,60.05,0,28.5697,-80.8191,54767,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,...,0.0,0.0,0.0,0.0,0.0,Weekend,Afternoon,June,2020,Second Half
4,2020-06-21 12:15:17,3526826139003047,3.19,0,44.2529,-85.0170,1126,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,...,0.0,0.0,0.0,0.0,0.0,Weekend,Afternoon,June,2020,Second Half
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,2020-12-31 23:59:07,30560609640617,43.77,0,40.4931,-91.8912,519,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,...,0.0,0.0,0.0,0.0,0.0,Weekday,Evening,December,2020,Second Half
555715,2020-12-31 23:59:09,3556613125071656,111.84,0,29.0393,-95.4401,28739,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,...,0.0,0.0,0.0,0.0,0.0,Weekday,Evening,December,2020,Second Half
555716,2020-12-31 23:59:15,6011724471098086,86.88,1,46.1966,-118.9017,3684,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,...,0.0,0.0,0.0,0.0,0.0,Weekday,Evening,December,2020,Second Half
555717,2020-12-31 23:59:24,4079773899158,7.99,0,44.6255,-116.4493,129,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,...,0.0,0.0,0.0,0.0,0.0,Weekday,Evening,December,2020,Second Half
555718,2020-12-31 23:59:34,4170689372027579,38.13,0,35.6665,-97.4798,116001,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,...,0.0,0.0,0.0,0.0,0.0,Weekday,Evening,December,2020,Second Half

In [37]:
df=df.drop('trans_date_trans_time',axis=1)

In [38]:
df

,cc_num,amt,gender,lat,long,city_pop,trans_num,unix_time,merch_lat,merch_long,...,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer,day_of_week,hour_of_day,month,year,day_of_month
0,2291163933867244,2.86,0,33.9659,-80.9355,333497,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,...,0.0,0.0,0.0,0.0,0.0,Weekend,Afternoon,June,2020,Second Half
1,3573030041201292,29.84,1,40.3207,-110.4360,302,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,...,0.0,0.0,0.0,0.0,0.0,Weekend,Afternoon,June,2020,Second Half
2,3598215285024754,41.28,1,40.6729,-73.5365,34496,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,...,0.0,0.0,0.0,0.0,0.0,Weekend,Afternoon,June,2020,Second Half
3,3591919803438423,60.05,0,28.5697,-80.8191,54767,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,...,0.0,0.0,0.0,0.0,0.0,Weekend,Afternoon,June,2020,Second Half
4,3526826139003047,3.19,0,44.2529,-85.0170,1126,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,...,0.0,0.0,0.0,0.0,0.0,Weekend,Afternoon,June,2020,Second Half
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,30560609640617,43.77,0,40.4931,-91.8912,519,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,...,0.0,0.0,0.0,0.0,0.0,Weekday,Evening,December,2020,Second Half
555715,3556613125071656,111.84,0,29.0393,-95.4401,28739,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,...,0.0,0.0,0.0,0.0,0.0,Weekday,Evening,December,2020,Second Half
555716,6011724471098086,86.88,1,46.1966,-118.9017,3684,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,...,0.0,0.0,0.0,0.0,0.0,Weekday,Evening,December,2020,Second Half
555717,4079773899158,7.99,0,44.6255,-116.4493,129,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,...,0.0,0.0,0.0,0.0,0.0,Weekday,Evening,December,2020,Second Half
555718,4170689372027579,38.13,0,35.6665,-97.4798,116001,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,...,0.0,0.0,0.0,0.0,0.0,Weekday,Evening,December,2020,Second Half

In [39]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['day_of_week'] = le.fit_transform(df['day_of_week'])
df['hour_of_day'] = le.fit_transform(df['hour_of_day'])
df['month'] = le.fit_transform(df['month'])
df['day_of_month'] = le.fit_transform(df['day_of_month'])
df['trans_num'] = le.fit_transform(df['trans_num'])

In [40]:
df

,cc_num,amt,gender,lat,long,city_pop,trans_num,unix_time,merch_lat,merch_long,...,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer,day_of_week,hour_of_day,month,year,day_of_month
0,2291163933867244,2.86,0,33.9659,-80.9355,333497,98699,1371816865,33.986391,-81.200714,...,0.0,0.0,0.0,0.0,0.0,1,0,3,2020,1
1,3573030041201292,29.84,1,40.3207,-110.4360,302,108785,1371816873,39.450498,-109.960431,...,0.0,0.0,0.0,0.0,0.0,1,0,3,2020,1
2,3598215285024754,41.28,1,40.6729,-73.5365,34496,433979,1371816893,40.495810,-74.196111,...,0.0,0.0,0.0,0.0,0.0,1,0,3,2020,1
3,3591919803438423,60.05,0,28.5697,-80.8191,54767,71993,1371816915,28.812398,-80.883061,...,0.0,0.0,0.0,0.0,0.0,1,0,3,2020,1
4,3526826139003047,3.19,0,44.2529,-85.0170,1126,190585,1371816917,44.959148,-85.884734,...,0.0,0.0,0.0,0.0,0.0,1,0,3,2020,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,30560609640617,43.77,0,40.4931,-91.8912,519,336391,1388534347,39.946837,-91.333331,...,0.0,0.0,0.0,0.0,0.0,0,1,1,2020,1
555715,3556613125071656,111.84,0,29.0393,-95.4401,28739,70372,1388534349,29.661049,-96.186633,...,0.0,0.0,0.0,0.0,0.0,0,1,1,2020,1
555716,6011724471098086,86.88,1,46.1966,-118.9017,3684,235088,1388534355,46.658340,-119.715054,...,0.0,0.0,0.0,0.0,0.0,0,1,1,2020,1
555717,4079773899158,7.99,0,44.6255,-116.4493,129,43546,1388534364,44.470525,-117.080888,...,0.0,0.0,0.0,0.0,0.0,0,1,1,2020,1
555718,4170689372027579,38.13,0,35.6665,-97.4798,116001,50595,1388534374,36.210097,-97.036372,...,0.0,0.0,0.0,0.0,0.0,0,1,1,2020,1

In [41]:
!pip install pandas_summary 
from pandas_summary import DataFrameSummary
dfs=DataFrameSummary(df)
dfs.columns_stats

WARNING: You are using pip version 20.2.3; however, version 24.0 is available.
You should consider upgrading via the 'c:\users\sharv\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: pandas_summary in c:\users\sharv\appdata\local\programs\python\python39\lib\site-packages (0.2.0)
Requirement already satisfied: numpy in c:\users\sharv\appdata\local\programs\python\python39\lib\site-packages (from pandas_summary) (1.25.1)
Requirement already satisfied: datatile in c:\users\sharv\appdata\local\programs\python\python39\lib\site-packages (from pandas_summary) (1.0.3)
Requirement already satisfied: pandas in c:\users\sharv\appdata\local\programs\python\python39\lib\site-packages (from pandas_summary) (2.2.1)
Requirement already satisfied: traceml<1.1 in c:\users\sharv\appdata\local\programs\python\python39\lib\site-packages (from datatile->pandas_summary) (1.0.8)
Requirement already satisfied: pytz>=2020.1 in c:\users\sharv\appdata\local\programs\python\python39\lib\site-packages (from pandas->pandas_summary) (2024.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sharv\appdata\local\programs\python\python39\lib\site-packages (from pandas->pandas_summary) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sharv\appdata\local\programs\python\python39\lib\site-packages (from pandas->pandas_summary) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\sharv\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas->pandas_summary) (1.16.0)

,cc_num,amt,gender,lat,long,city_pop,trans_num,unix_time,merch_lat,merch_long,...,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer,day_of_week,hour_of_day,month,year,day_of_month
counts,555719,555719,555719,555719,555719,555719,555719,555719,555719,555719,...,555719,555719,555719,555719,555719,555719,555719,555719,555719,555719
uniques,924,37256,2,910,910,835,555719,544760,546490,551770,...,2,2,2,2,2,2,3,7,1,2
missing,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
missing_perc,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,...,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%
types,numeric,numeric,bool,numeric,numeric,numeric,numeric,numeric,numeric,numeric,...,bool,bool,bool,bool,bool,bool,numeric,numeric,constant,bool

In [42]:
from sklearn.model_selection import train_test_split

X = df.drop(['is_fraud'], axis=1)
y = df['is_fraud']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [43]:

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train,y_train)
print(model.score(X_test,y_test))

y_pred=model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion:")
print(conf_matrix)

0.9981765397442357
Confusion:
[[166068      8]
 [   296    344]]